# Generated by Django 4.1.1 on 2022-10-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_transactionid_order_transactionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transactionId',
        ),
        migrations.AddField(
            model_name='order',
            name='transactionID',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
